# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |           # runs during prebuild
    pip3 install gym 
    pip3 install numpy
    pip3 install tensorflow
    pip3 install tensorflow_probability
    command: echo 'start script'

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
#ports:
#  - port: 3000
#    onOpen: open-preview
